project_id = "olfucdwmegdnczwpgaeg"

[functions.send-campaign-batch]
verify_jwt = false

[functions.twilio-inbound]
verify_jwt = false

[functions.twilio-status]
verify_jwt = false

[functions.check-no-reply]
verify_jwt = false

[functions.fetch-place]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.retell-start-call]
verify_jwt = false

[functions.retell-webhook]
verify_jwt = false
