import { listNotificationRecipients } from "@ruleradar/db";
import { AppTabs } from "../../ui";

export const dynamic = "force-dynamic";

export default async function SettingsPage() {
  const recipients = await listNotificationRecipients();
  const first = recipients[0];

  return (
    <main className="page">
      <AppTabs />
      <h1>Organization Settings</h1>
      <div className="grid two">
        <section className="card">
          <h2>Alert preferences</h2>
          <form action="/api/settings/notifications" method="post">
            <label className="form-row">Delivery mode<select name="deliveryMode" className="input" defaultValue={first?.immediate ? "immediate" : "digest"}><option value="immediate">Immediate for important changes</option><option value="digest">Daily digest only</option></select></label>
            <label className="form-row">Recipient email<input name="recipientEmail" className="input" defaultValue={first?.recipientEmail || "payroll@example.se"} required /></label>
            <label className="form-row">Topics<input name="topics" className="input" defaultValue={first?.topics.join(", ") || ""} placeholder="blank means all topics" /></label>
            <button className="button" type="submit">Save</button>
          </form>
          <p className="muted" style={{ marginTop: 12 }}>{recipients.length} active recipient{recipients.length === 1 ? "" : "s"} configured.</p>
        </section>
        <section className="card">
          <h2>Billing</h2>
          <p>Plan: Team</p>
          <p className="muted">Stripe portal links are generated by the billing API when Stripe secrets are configured.</p>
          <form action="/api/billing/checkout?plan=team" method="post">
            <button className="button secondary" type="submit">Open billing</button>
          </form>
        </section>
      </div>
    </main>
  );
}
